spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdatajpa?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 5

  jpa:
    database: mysql
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG